---
title: "615 Final Report"
author: "Jinfei Xue"
date: "Dec 17, 2018"
output: word_document
subtitle: "Mass Shootings Analysis in USA"
---

```{r, echo=FALSE,warning=FALSE, message=FALSE}
library(tm)
library(tidyr)
library(tidytext)
library(dplyr)
library(rgdal)
library(plotly)
library(ggplot2)
library(benford.analysis)
library(leaflet)
library(wordcloud2)
```

# Data Import

```{r}
MSD_S <- read.csv("Stanford_MSA_Database.csv")
```

# Data Cleaning

```{r}
# Generate a new column
MSD_S$Total.Number.of.Injured <- MSD_S$Number.of.Civilian.Injured +
  MSD_S$Number.of.Enforcement.Injured

# Select interesting variables
MSD <- MSD_S %>%
  dplyr::select(Title, Location, City, State, Latitude, Longitude, 
         Total.Number.of.Injured, Total.Number.of.Fatalities,
         Total.Number.of.Victims, Date, Day.of.Week,
         Number.of.shooters, Average.Shooter.Age, Shooter.Sex, Shooter.Race, 
         Type.of.Gun...General, Total.Number.of.Guns, 
         Fate.of.Shooter.at.the.scene, Fate.of.Shooter, Shooter.s.Cause.of.Death,
         School.Related, Place.Type, Targeted.Victim.s...General, 
         History.of.Mental.Illness...General, Military.Experience)
  
# Check NA
sapply(MSD, function(x) sum(is.na(x)))
  
# Structure of the data
str(MSD)
summary(MSD)

# Transform the class of variables
#levels(MSD$Shooter.Race)


# Date
MSD$Year <- format(as.Date(MSD$Date, format="%m/%d/%Y"),"%Y")
MSD$Month <- format(as.Date(MSD$Date, format="%m/%d/%Y"),"%m")

```


# plotly: Plot the total number of victims by timeline

```{r plotly, warning=FALSE, message=FALSE}
plot_ly(data = MSD
        ,type = 'scatter'
        ,mode = 'markers' 
        ,hoverinfo = 'text'
        ,x = ~Month
        ,y = ~Year
        ,size = ~Total.Number.of.Victims
        ,color = ~Shooter.Sex
        ,colors = c('Red', 'Blue', 'Green', 'Black')
        ,alpha = 0.6
        ,text = ~paste("Title: ", Title
               ,"\nLocation: ", Location
               ,'\n Date: ', Date 
               ,'\n Total victims : ', Total.Number.of.Victims)) %>% 
  layout(title = "Mass Shootings in US by years and month"
         , xaxis = list(title = "Month")
         , yaxis = list(title = "Years"))
```

# plotly: Bar plot with Total victims by Years and Race

```{r,warning=FALSE, message=FALSE}
# Only year
MSD_yv <- MSD %>%
  select(Year, Total.Number.of.Victims, Total.Number.of.Injured, 
         Total.Number.of.Fatalities) %>%
  group_by(Year) %>%
  mutate(Sum.Victims=sum(Total.Number.of.Victims)) %>%
  mutate(Sum.Injured=sum(Total.Number.of.Injured)) %>%
  mutate(Sum.Fatalities=sum(Total.Number.of.Fatalities)) %>%
  select(Year, Sum.Victims, Sum.Injured, Sum.Fatalities) %>%
  unique()

plot_ly(data = MSD_yv
        ,type = 'bar'
        ,mode = 'markers' 
        ,hoverinfo = 'text'
        ,x = ~Year
        ,y = ~ `Sum.Victims` 
        ,color = 'Tomato'
        ,alpha = 0.9
        ,text = ~paste(
               'Injured : ', Sum.Injured,
               '\n Fatalities : ', Sum.Fatalities
)) %>% 
  layout(title = "Number of Total Victims by Years"
         , xaxis = list(title = "Year")
         , yaxis = list(title = "Number of Total Victims"))


# year + gender
MSD_ygv <- MSD %>%
  select(Year, Shooter.Sex, Total.Number.of.Victims) %>%
  group_by(Year, Shooter.Sex) %>%
  mutate(Sum.Victims=sum(Total.Number.of.Victims)) %>%
  select(Year, Shooter.Sex, Sum.Victims) %>%
  unique()

plot_ly(data = MSD_ygv
        ,type = 'bar'
        ,mode = 'markers'
        ,x = ~Year
        ,y = ~Sum.Victims
        ,color = ~Shooter.Sex
        ,alpha = 0.9) %>% 
  layout(title = "Total Victims by Gender"
         , xaxis = list(title = "Year")
         , yaxis = list(title = "Number of Total Victims")
         , showlegend = T
         , barmode = 'stack'
         , position = 1
         , xaxis = list(title = "")
         , yaxis = list(title = "")
         , legend = list(x = 0, y = 1)
         , hovermode = 'compare')

# year + race
MSD_ygr <- MSD %>%
  select(Year, Shooter.Race, Total.Number.of.Victims) %>%
  group_by(Year) %>%
  mutate(Sum.Victims=sum(Total.Number.of.Victims)) %>%
  select(Year, Shooter.Race, Sum.Victims) %>%
  unique()

plot_ly(data = MSD_ygr
        ,type = 'bar'
        ,mode = 'markers'
        ,x = ~Year
        ,y = ~Sum.Victims
        ,color = ~Shooter.Race
        ,alpha = 0.9) %>% 
  layout(title = "Total Victims by Shooter Race"
         , xaxis = list(title = "Year")
         , yaxis = list(title = "Number of Total Victims")
         , showlegend = T
         , barmode = 'stack'
         , position = 1
         , xaxis = list(title = "")
         , yaxis = list(title = "")
         , legend = list(x = 0, y = 1)
         , hovermode = 'compare')



```


# Leaflet: Total number of victims in each state

```{r map_victims, message=FALSE, warning=FALSE}
MSD_state <- MSD %>%
  select(State, Total.Number.of.Injured, Total.Number.of.Victims) %>%
  group_by(State) %>%
  mutate(Sum.Injured=sum(Total.Number.of.Injured)) %>%
  mutate(Sum.Victims=sum(Total.Number.of.Victims)) %>%
  select(State, Sum.Injured, Sum.Victims) %>%
  unique()

#draw map using leaflet
# library(sp)
# library(dplyr)
# library(WDI)
## Download data from Natural Earth
url <- "http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/50m/cultural/ne_50m_admin_1_states_provinces.zip"
tmp <- tempdir()
file <- basename(url)
download.file(url, file)
unzip(file, exdir = tmp)
## Read the data into R
state_spatial <- readOGR(dsn=tmp,
                         layer = "ne_50m_admin_1_states_provinces", 
                         encoding = "UTF-8")
#get the states name in spatial data
a<-state_spatial@data[["gn_name"]] #because the state name in "states" are in lower format
# state_spatial@data[["gn_name"]]<-a
data<-sp::merge(state_spatial,MSD_state,by.x="gn_name",by.y="State",sort=FALSE,duplicateGeoms = TRUE,all.x=FALSE)
labels <- sprintf(
  "<strong>%s</strong><br/>%s Total number of injured<br/>%g Total number of victims",
  data$gn_name, data$Sum.Injured, data$Sum.Victims
) %>% lapply(htmltools::HTML)


# leaflet
m <- leaflet(data) %>%
  addTiles()%>%
  setView(-96, 37.8, 4)
#bins
pal <- colorQuantile("YlOrRd", domain = MSD_state$Sum.Victims)
#pal(states$Donations)
m_victims <- m %>% addPolygons(
  fillColor = ~pal(data$Sum.Victims),
  weight = 2,
  opacity = 1,
  color = "white",
  dashArray = "3",
  fillOpacity = 0.7,
  highlight = highlightOptions(
    weight = 5,
    color = "#666",
    dashArray = "",
    fillOpacity = 0.7,
    bringToFront = TRUE),
  label = labels,
  labelOptions = labelOptions(
    style = list("font-weight" = "normal", padding = "3px 8px"),
    textsize = "15px",
    direction = "auto")
) %>%
  addLegend(pal = pal, values = ~Sum.Victims, opacity = 0.7, title = "Quantile in Total Number of Victims",
            position = "bottomright")
m_victims
```

```{r}
# location
MSD_lo <- MSD %>%
  select(Place.Type, School.Related,Type.of.Gun...General,Total.Number.of.Victims) %>%
  group_by(Place.Type) %>%
  mutate(Sum.Victims=sum(Total.Number.of.Victims)) %>%
  select(Year, Shooter.Sex) %>%
  unique()


ggplot(data = Vtrain) +
  aes(x = HiveCondition, y = FS_Honey, fill = HiveCondition) +
  geom_boxplot() +
  labs(title = 'Frame Sides of Honey per Box vs. Hive Condition',
    x = 'Hive Condition',
    y = 'Frame Sides of Honey per Box') +  
  theme(axis.text.x = element_text(angle = 45, hjust = 1))



```



```{r}
g <- list(
    scope = 'usa'
  , projection = list(type = 'albers usa')
  , showland = TRUE
  , landcolor = 'black'
  , subunitwidth = 1
  , countrywidth = 1
 , subunitcolor = toRGB("white")
 , countrycolor = toRGB("white")
)

plot_geo(MSD
         #, locationmode = 'USA-states'
         , sizes = c(10, 300)) %>%
  add_markers(
    x = ~Longitude
    , y = ~Latitude
    , size = ~Total.Number.of.Victims
    , color = ~Total.Number.of.Fatalities
    , colors = colorRamp(c("yellow", "red", "black"))
    , hoverinfo = "text"
    , text = ~paste(MSD$Title
                    , '\n Fatalities: ', MSD$Total.Number.of.Fatalities
                    , '\n Injured: ', MSD$Total.Number.of.Injured)
  ) %>%
  layout(title = 'Geography of Mass Shooting in US', geo = g)

```


